"""empty message

Revision ID: 2b071c76f6fb
Revises: 8e5326055816
Create Date: 2021-03-21 13:33:58.084790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b071c76f6fb'
down_revision = '8e5326055816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_title', table_name='task')
    op.drop_table('task')
    op.add_column('to_do_list', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'to_do_list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'to_do_list', type_='foreignkey')
    op.drop_column('to_do_list', 'user_id')
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=246), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_title', 'task', ['title'], unique=False)
    # ### end Alembic commands ###
